export function buildReport({ domain, summary, findings, usedLlmLabel }) {
  const order = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
  const list = [...(findings || [])].sort((a, b) => (order[a.severity] ?? 9) - (order[b.severity] ?? 9));
  const bySev = (s) => list.filter((f) => f.severity === s).length;
  const lines = [];
  lines.push(`# Security recon report — ${domain}`);
  lines.push("");
  lines.push(`Generated by xalgo-ops (${usedLlmLabel || "local writer"}).`);
  lines.push("Authorized testing only. Passive OSINT + HTTP template scan. Not a full pentest.");
  lines.push("");
  lines.push("## Snapshot");
  lines.push(`- Subdomains: ${summary.subdomainCount || 0}`);
  lines.push(`- Hosts scanned: ${summary.hostsScanned || 0}`);
  lines.push(`- Archive URLs: ${summary.urlCount || 0}`);
  lines.push(`- Findings: ${list.length} (C ${bySev("critical")} / H ${bySev("high")} / M ${bySev("medium")} / L ${bySev("low")} / I ${bySev("info")})`);
  lines.push("");
  lines.push("## Attack paths");
  const paths = list.filter((f) => ["critical", "high"].includes(f.severity)).slice(0, 8);
  if (!paths.length) {
    lines.push("1. Authenticated IDOR/BOLA on any discovered API or GraphQL.");
    lines.push("2. Live-check interesting archive paths (admin, backup, debug).");
    lines.push("3. Confirm dangling CNAMEs before filing takeover.");
  } else {
    paths.forEach((f, i) => {
      lines.push(`${i + 1}. **${f.severity.toUpperCase()} — ${f.title}**`);
      lines.push(`   Asset: \`${f.asset}\``);
      lines.push(`   Evidence: ${f.evidence}`);
      lines.push(`   Next: reproduce on the live host, keep requests non-destructive, attach response in the program report.`);
    });
  }
  lines.push("");
  lines.push("## All findings");
  for (const f of list) {
    lines.push(`### ${f.severity.toUpperCase()} — ${f.title}`);
    lines.push(`- Asset: ${f.asset}`);
    if (f.template) lines.push(`- Template: ${f.template}`);
    if (f.cwe) lines.push(`- ${f.cwe}`);
    lines.push(`- Evidence: ${f.evidence}`);
    lines.push("");
  }
  lines.push("## Coverage limits");
  lines.push("- No authenticated session testing unless you supplied cookies (not enabled here).");
  lines.push("- Full Nuclei template pack runs only when the optional worker is attached.");
  lines.push("- Do not file unverified takeover or secret findings.");
  return lines.join("\n");
}
