export const TEMPLATES = [
  { id: "git-head", name: "Exposed Git HEAD", severity: "critical", tags: ["misconfig", "git"], method: "GET", path: "/.git/HEAD", matchers: [{ type: "regex", regex: "^(ref: |[0-9a-f]{40})" }] },
  { id: "git-config", name: "Exposed Git config", severity: "high", tags: ["misconfig", "git"], method: "GET", path: "/.git/config", matchers: [{ type: "word", words: ["[core]"] }] },
  { id: "dotenv", name: "Exposed .env", severity: "critical", tags: ["secret"], method: "GET", path: "/.env", matchers: [{ type: "regex", regex: "(?i)(aws_|db_|api_|secret|password|token).{0,20}=" }, { type: "status", status: [200] }] },
  { id: "env-bak", name: "Exposed env backup", severity: "high", tags: ["secret"], method: "GET", path: "/.env.bak", matchers: [{ type: "regex", regex: "(?i)(aws_|db_|api_|secret|password)=" }] },
  { id: "wp-config-bak", name: "wp-config backup", severity: "critical", tags: ["wordpress", "secret"], method: "GET", path: "/wp-config.php.bak", matchers: [{ type: "word", words: ["DB_PASSWORD"] }] },
  { id: "ds-store", name: "Exposed .DS_Store", severity: "low", tags: ["exposure"], method: "GET", path: "/.DS_Store", matchers: [{ type: "binary", magic: "Bud1" }] },
  { id: "server-status", name: "Apache server-status", severity: "medium", tags: ["apache"], method: "GET", path: "/server-status", matchers: [{ type: "word", words: ["Apache Server Status"] }] },
  { id: "phpinfo", name: "phpinfo exposed", severity: "medium", tags: ["php"], method: "GET", path: "/phpinfo.php", matchers: [{ type: "word", words: ["PHP Version"] }] },
  { id: "actuator-env", name: "Spring actuator env", severity: "high", tags: ["spring"], method: "GET", path: "/actuator/env", matchers: [{ type: "word", words: ["propertySources"] }] },
  { id: "actuator-health", name: "Spring actuator health", severity: "info", tags: ["spring"], method: "GET", path: "/actuator/health", matchers: [{ type: "word", words: ["status"] }] },
  { id: "actuator-heapdump", name: "Spring heapdump", severity: "critical", tags: ["spring"], method: "GET", path: "/actuator/heapdump", matchers: [{ type: "status", status: [200] }, { type: "header", header: "content-type", regex: "octet|binary" }] },
  { id: "swagger", name: "Swagger UI", severity: "medium", tags: ["api"], method: "GET", path: "/swagger-ui.html", matchers: [{ type: "word", words: ["Swagger UI"] }] },
  { id: "swagger-json", name: "OpenAPI JSON", severity: "medium", tags: ["api"], method: "GET", path: "/swagger.json", matchers: [{ type: "regex", regex: "\"(swagger|openapi)\"" }] },
  { id: "openapi", name: "openapi.json", severity: "medium", tags: ["api"], method: "GET", path: "/openapi.json", matchers: [{ type: "regex", regex: "\"openapi\"" }] },
  { id: "v3-api-docs", name: "Spring v3 api-docs", severity: "medium", tags: ["api"], method: "GET", path: "/v3/api-docs", matchers: [{ type: "regex", regex: "\"openapi\"" }] },
  { id: "graphql", name: "GraphQL endpoint", severity: "info", tags: ["graphql"], method: "POST", path: "/graphql", headers: { "content-type": "application/json" }, body: "{\"query\":\"{__typename}\"}", matchers: [{ type: "regex", regex: "__typename|data|errors" }] },
  { id: "graphql-introspect", name: "GraphQL introspection", severity: "medium", tags: ["graphql"], method: "POST", path: "/graphql", headers: { "content-type": "application/json" }, body: "{\"query\":\"{__schema{queryType{name}}}\"}", matchers: [{ type: "word", words: ["queryType"] }] },
  { id: "debug-pprof", name: "Go pprof", severity: "medium", tags: ["debug"], method: "GET", path: "/debug/pprof/", matchers: [{ type: "word", words: ["/debug/pprof/"] }] },
  { id: "metrics", name: "Prometheus metrics", severity: "low", tags: ["metrics"], method: "GET", path: "/metrics", matchers: [{ type: "regex", regex: "(?m)^# HELP " }] },
  { id: "elmah", name: "ELMAH", severity: "medium", tags: ["aspnet"], method: "GET", path: "/elmah.axd", matchers: [{ type: "word", words: ["Error Log for"] }] },
  { id: "trace.axd", name: "ASP.NET trace", severity: "medium", tags: ["aspnet"], method: "GET", path: "/trace.axd", matchers: [{ type: "word", words: ["Application Trace"] }] },
  { id: "wp-json-users", name: "WP user enum", severity: "low", tags: ["wordpress"], method: "GET", path: "/wp-json/wp/v2/users", matchers: [{ type: "regex", regex: "\"slug\"" }] },
  { id: "wp-login", name: "WordPress login", severity: "info", tags: ["wordpress"], method: "GET", path: "/wp-login.php", matchers: [{ type: "word", words: ["wp-submit"] }] },
  { id: "xmlrpc", name: "WordPress xmlrpc", severity: "info", tags: ["wordpress"], method: "GET", path: "/xmlrpc.php", matchers: [{ type: "word", words: ["XML-RPC server accepts POST"] }] },
  { id: "drone", name: "Drone CI", severity: "medium", tags: ["ci"], method: "GET", path: "/", hostHint: "drone", matchers: [{ type: "word", words: ["Drone"] }] },
  { id: "jenkins", name: "Jenkins", severity: "medium", tags: ["ci"], method: "GET", path: "/login", matchers: [{ type: "word", words: ["Jenkins"] }] },
  { id: "kibana", name: "Kibana", severity: "medium", tags: ["elastic"], method: "GET", path: "/app/kibana", matchers: [{ type: "word", words: ["kibana"] }] },
  { id: "grafana", name: "Grafana", severity: "medium", tags: ["grafana"], method: "GET", path: "/login", matchers: [{ type: "word", words: ["Grafana"] }] },
  { id: "es-unauth", name: "Elasticsearch unauth", severity: "high", tags: ["elastic"], method: "GET", path: "/", portHint: 9200, matchers: [{ type: "word", words: ["cluster_name", "You Know, for Search"] }] },
  { id: "firebase", name: "Firebase open DB hint", severity: "info", tags: ["firebase"], method: "GET", path: "/.json", matchers: [{ type: "status", status: [200] }] },
  { id: "s3-list", name: "S3 listing via website", severity: "high", tags: ["aws"], method: "GET", path: "/", matchers: [{ type: "word", words: ["<ListBucketResult"] }] },
  { id: "dir-list", name: "Directory listing", severity: "low", tags: ["misconfig"], method: "GET", path: "/", matchers: [{ type: "regex", regex: "Index of /|<title>Index of" }] },
  { id: "robots", name: "robots.txt", severity: "info", tags: ["recon"], method: "GET", path: "/robots.txt", matchers: [{ type: "regex", regex: "(?i)disallow:" }] },
  { id: "security-txt", name: "security.txt", severity: "info", tags: ["recon"], method: "GET", path: "/.well-known/security.txt", matchers: [{ type: "regex", regex: "(?i)contact:" }] },
  { id: "backup-zip", name: "Backup zip at root", severity: "high", tags: ["backup"], method: "GET", path: "/backup.zip", matchers: [{ type: "header", header: "content-type", regex: "zip|octet" }, { type: "status", status: [200] }] },
  { id: "dump-sql", name: "SQL dump", severity: "critical", tags: ["backup"], method: "GET", path: "/dump.sql", matchers: [{ type: "regex", regex: "(?i)(INSERT INTO|CREATE TABLE)" }] },
  { id: "adminer", name: "Adminer", severity: "high", tags: ["db"], method: "GET", path: "/adminer.php", matchers: [{ type: "word", words: ["Adminer", "Login"] }] },
  { id: "phpmyadmin", name: "phpMyAdmin", severity: "medium", tags: ["db"], method: "GET", path: "/phpmyadmin/", matchers: [{ type: "word", words: ["phpMyAdmin"] }] },
  { id: "server-info", name: "Apache server-info", severity: "medium", tags: ["apache"], method: "GET", path: "/server-info", matchers: [{ type: "word", words: ["Server Information"] }] },
  { id: "cgi-printenv", name: "printenv CGI", severity: "medium", tags: ["cgi"], method: "GET", path: "/cgi-bin/printenv.pl", matchers: [{ type: "word", words: ["SERVER_SOFTWARE"] }] },
  { id: "config-json", name: "config.json", severity: "medium", tags: ["secret"], method: "GET", path: "/config.json", matchers: [{ type: "regex", regex: "(?i)(apiKey|api_key|secret|private)" }] },
  { id: "settings-js", name: "settings.js secrets", severity: "medium", tags: ["secret"], method: "GET", path: "/settings.js", matchers: [{ type: "regex", regex: "(?i)(apiKey|secret|token)\s*[:=]" }] },
  { id: "well-known-openid", name: "OIDC discovery", severity: "info", tags: ["oauth"], method: "GET", path: "/.well-known/openid-configuration", matchers: [{ type: "word", words: ["issuer"] }] },
  { id: "oauth-wellknown", name: "OAuth AS metadata", severity: "info", tags: ["oauth"], method: "GET", path: "/.well-known/oauth-authorization-server", matchers: [{ type: "word", words: ["issuer"] }] },
  { id: "telescope", name: "Laravel Telescope", severity: "high", tags: ["laravel"], method: "GET", path: "/telescope", matchers: [{ type: "word", words: ["Telescope"] }] },
  { id: "horizon", name: "Laravel Horizon", severity: "medium", tags: ["laravel"], method: "GET", path: "/horizon", matchers: [{ type: "word", words: ["Horizon"] }] },
  { id: "debugbar", name: "Laravel debugbar", severity: "medium", tags: ["laravel"], method: "GET", path: "/_debugbar/open", matchers: [{ type: "status", status: [200] }] },
  { id: "django-debug", name: "Django debug", severity: "medium", tags: ["django"], method: "GET", path: "/admin", matchers: [{ type: "word", words: ["Django administration"] }] },
  { id: "rails-assets", name: "Rails assets pipeline hint", severity: "info", tags: ["rails"], method: "GET", path: "/assets/application.js", matchers: [{ type: "status", status: [200] }] },
  { id: "next-server", name: "Next.js server ident", severity: "info", tags: ["next"], method: "GET", path: "/", matchers: [{ type: "header", header: "x-powered-by", regex: "Next.js" }] },
  { id: "cors-star", name: "CORS ACAO echo check", severity: "info", tags: ["cors"], method: "GET", path: "/", headers: { origin: "https://evil.example" }, matchers: [{ type: "header", header: "access-control-allow-origin", regex: "\\*|evil\\.example" }] }
];

export const PACKS = {
  quick: ["git-head", "git-config", "dotenv", "actuator-env", "swagger-json", "openapi", "graphql-introspect", "wp-json-users", "s3-list", "telescope", "adminer", "dump-sql", "config-json", "metrics", "phpinfo"],
  full: TEMPLATES.map((t) => t.id),
  secrets: ["dotenv", "env-bak", "wp-config-bak", "config-json", "settings-js", "actuator-env", "actuator-heapdump"],
  panels: ["jenkins", "grafana", "kibana", "phpmyadmin", "adminer", "swagger", "wp-login"]
};
